### ISSUE TITLE
Create a good macro for the macro slides

### ISSUE THREAD

**Issue by lwjohnst86** [codeasmanuscript/workshops#2]
We can develop a macro here, at least to start. Then we can meet in person later on to discuss :)

**Comment by lwjohnst86** [comment]
We could use something like this that I have already made here (https://github.com/codeasmanuscript/workshops/blob/master/lessons/macros/practice/code.sas)

```
%macro means(vars, where=, class=, data=);
    proc means data=&data;
        var &vars;
        where &where;
        class &class;
    run;
    %mend means;

%let length = Length1 Length2 Length3;
%let others = Weight Height Width;

%means(&length, where = Weight < 200,
    class = Species, data = sashelp.fish);

%means(&others, class = Species, data = sashelp.fish);
```

**Comment by lwjohnst86** [comment]
The nice thing is the example demonstrates positional vs keyword macro arguments

**Comment by lwjohnst86** [comment]
I mean, the example you gave in the slides isn't bad, the only thing is that it isn't reproducible (meaning they can't actually run the code).

At least use the sashelp datasets or something...?

**Comment by daivanielsen** [comment]
Ok yeah that code is great. Can we manipulate it in a couple of different ways to illustrate how macros cut back on the need to type out code?

**Comment by daivanielsen** [comment]
The other code example I'm working on is showing how to use macros to manipulate variables (like transformations) and output printing. I'll use the SAS fish database to keep it consistent. I think this is a way of applying macros that everyone can use in their analyses, even though it's not actually an example of running a stats test.

**Comment by daivanielsen** [comment]
Oh and I have another question. There's an example of bad code in the practice folder, but I think that's also not reproducible for the workshop (we won't be using that dataset, correct?) I guess I can just expand the SAS fish example for each different fish species to show how the macro condenses the amount of typing needed?

**Comment by daivanielsen** [comment]
Also I can't make it in to FG today to check room availability, but I'll be in tomorrow. I can book the room first thing and then circulate an email with the eventbrite link through Louisa. I think that gives people enough time to RSVP.

**Comment by lwjohnst86** [comment]
OK, no problem. I wasn't in anyway either.

Yes, that would be fine re: the macros. Can you post an example? Or put on the repo.

And yes, the bad code example is not reproducible, but I would eventually like it to be.  Haven't got around to it yet.

We said May 26 from 12:30-5:00 right? Just forgot to put it in my calender.

**Comment by daivanielsen** [comment]
Yup that's the date! Yes I'll post an example of the printing...just have to finish a few things for Ahmed today. I'll post in the early evening :)
