### ISSUE TITLE
Review survey contents

### ISSUE THREAD

**Issue by lwjohnst86** [codeasmanuscript/workshops#3]
We'll need to change how we do this if we want feedback on files.. We'll have to do it through pull requests and not on through direct pushing... 

Anyway, I've developed/updated the initial survey and the ticket out the door survey. I want to make a Google Forms from the surveys (so it is not paper based and the responses are instantly electronic), but I would like some input on the questions in the survey.  So @thesarahmeister (or @daivanielsen), would you mind looking the below files? Thank you! :)
- The [registration survey](https://github.com/codeasmanuscript/workshops/blob/master/survey/initial/initial.md)
- The [ticket out the door survey](https://github.com/codeasmanuscript/workshops/blob/master/survey/eval/ticketOutTheDoor.md)

You can make comments here in this issue.

**Comment by ghost** [comment]
Should we ask for names or leave it anonymous? (for the registration)

**Comment by lwjohnst86** [comment]
For the registration, we'll need the names to cross-ref with GPS's list of registered students. Otherwise, I would rather keep it anonymous as well! When I put the responses from the survey onto github, I'll remove the names.
